---
name: Release bundle

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundle
        run: |
          zip -r gsjackctl@cbix.de.zip * -x .* test/\*
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: gsjackctl ${{ github.ref }}
          generate_release_notes: true
          files: gsjackctl@cbix.de.zip
